<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="Abhisek-mohanta" failures="0" tests="19" name="Test" time="7.981" errors="0" timestamp="2024-03-04T12:18:25 IST">
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="validateFacebookHomePage" time="0.029"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="validateProfileName" time="0.004"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="uploadProfilePicture" time="0.001"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="uploadCoverPhoto" time="0.005"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="clickOnEditProfileAddDetailsInBioSections" time="0.001"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="clicOnPostGoToIntoAddDetailsInAddBio" time="0.001"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="clicOnPostGoToIntoClickOnEditDetailsAddWorkPlace" time="0.006"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="clicOnPostGoToIntoClickOnEditFeaturedAddOneFeaturedPhotos" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewAddWorkplace" time="0.004"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewAddSecondaryHighSchool" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewAddUniversity" time="0.001"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewAddCurrentCity" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewAddHomeTown" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewAddRelationShipStatus" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="gotoAboutClickOnOverviewEditPhoneNumber" time="0.001"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="go_to_notification" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="go_to_marketPlace" time="0.006"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="like_any_post" time="0.002"/>
  <testcase classname="testcases.FaceBook_L2_AutomationTest" name="click_on_events" time="0.001"/>
=======
<testsuite ignored="0" hostname="Abhisek-mohanta" failures="23" tests="34" name="Test" time="46.448" errors="0" timestamp="2024-03-04T10:29:30 IST">
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="check_Shop_Menu" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.check_Shop_Menu(Practice_Automation_L1_TestCases.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- check_Shop_Menu -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="click_Shop_Menu" time="3.413"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="navigate_to_Shop_page" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.navigate_to_Shop_page(Practice_Automation_L1_TestCases.java:100)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigate_to_Shop_page -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="click_on_cart" time="3.131"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="navigateTobasketpage" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.navigateTobasketpage(Practice_Automation_L1_TestCases.java:137)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigateTobasketpage -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Home_menu" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Home_menu(Practice_Automation_L1_TestCases.java:151)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Home_menu -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Click_on_Home" time="3.19"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="navigateToHomePage" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.navigateToHomePage(Practice_Automation_L1_TestCases.java:191)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigateToHomePage -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="new_arrival_is_present" time="3.118"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="seleniumu_Ruby_is_present" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.seleniumu_Ruby_is_present(Practice_Automation_L1_TestCases.java:222)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- seleniumu_Ruby_is_present -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="one_product_isClickable" time="3.115"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="navigates_to_Selenium_Ruby" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.navigates_to_Selenium_Ruby(Practice_Automation_L1_TestCases.java:263)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigates_to_Selenium_Ruby -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="add_to_basket" time="3.097"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Click_on_add_to_basket" time="3.167"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="verify_message" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.verify_message(Practice_Automation_L1_TestCases.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verify_message -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="GoToCart" time="3.157"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="CheckItem" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.CheckItem(Practice_Automation_L1_TestCases.java:350)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- CheckItem -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Apply_Coupon" time="3.126"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Price_Defined" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Price_Defined(Practice_Automation_L1_TestCases.java:386)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Price_Defined -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Price_Defined_in_correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Price_Defined_in_correct_Format(Practice_Automation_L1_TestCases.java:404)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Price_Defined_in_correct_Format -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Quantity_Defined" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Quantity_Defined(Practice_Automation_L1_TestCases.java:422)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Quantity_Defined -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="quantity_Defined_in_correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.quantity_Defined_in_correct_Format(Practice_Automation_L1_TestCases.java:439)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- quantity_Defined_in_correct_Format -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Total_Defined" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Total_Defined(Practice_Automation_L1_TestCases.java:456)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Total_Defined -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Total_Defined_in_Correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Total_Defined_in_Correct_Format(Practice_Automation_L1_TestCases.java:473)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Total_Defined_in_Correct_Format -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Tax_Defined" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Tax_Defined(Practice_Automation_L1_TestCases.java:489)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Tax_Defined -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Tax_Defined_in_correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Tax_Defined_in_correct_Format(Practice_Automation_L1_TestCases.java:506)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Tax_Defined_in_correct_Format -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="remove_option_is_present" time="3.164"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="remove" time="3.194"/>
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="ValidateAnRemoveMessage" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.ValidateAnRemoveMessage(Practice_Automation_L1_TestCases.java:563)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ValidateAnRemoveMessage -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="updateQuantity" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.updateQuantity(Practice_Automation_L1_TestCases.java:578)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- updateQuantity -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Update_Basket" time="0.0">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Update_Basket(Practice_Automation_L1_TestCases.java:595)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Update_Basket -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Proceed_to_checkout" time="0.0">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Proceed_to_checkout(Practice_Automation_L1_TestCases.java:613)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Proceed_to_checkout -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="Click_Proceed_to_checkout" time="0.0">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Practice_Automation_L1_TestCases.Click_Proceed_to_checkout(Practice_Automation_L1_TestCases.java:631)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Click_Proceed_to_checkout -->
  <testcase classname="testcases.Practice_Automation_L1_TestCases" name="navigate_to_Billing_Details_page" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Practice_Automation_L1_TestCases.navigate_to_Billing_Details_page(Practice_Automation_L1_TestCases.java:653)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigate_to_Billing_Details_page -->
>>>>>>> 121b450 (added the new usecases for demo automation testing site)
</testsuite> <!-- Test -->
